const ResumeApi = [
    {
      id: 1,
      category: "education",
      year: "Northeastern University | MA | USA (2021 - 2023)",
      title: "Master of Science in Information Systems",
      desc1: "•	Enrolled Courses: Application Engineering and Development, Database Management and Database Design, Data Structures and Algorithms, Web Design and User Experience Engineering, Concepts of Object-Oriented Design",
      desc2:"",
      desc3:"",
      rate: "3.8/4",
    },
    {
      id: 2,
      category: "education",
      year: "University of Mumbai | MH | India (2012 - 2016)",
      title: "Bachelor of Engineering in Mechanical",
      desc1: "•	Related Courses: Learned Computer Science fundamentals in Structured Programming Approach, Database Information and Retrieval System",
      desc2:"",
      desc3:"",
      rate: "6.8/10",
    },
    {
      id: 3,
      category: "education",
      year: "Prognoz Technologies | India (2017 - 2018) ",
      title: "Full-Stack Development Certification(.Net)",
      desc1: "•	Got exposure to technologies like .Net, ASP.Net, WPF, HTML, CSS, C#, SQL Server, etc.",
      desc2: "•	Soft skills training",
      desc3: "",
      rate: "Certified",
    },
    {
      id: 4,
      category: "experience",
      year: "Northeastern University, Boston (May 2021 - Present)",
      title: "Graduate Teaching Assistant",
      desc1: "•	Creating and grading assignments and quizzes for Professor Vishal Chawla's course Web Design and User Experience Engineering.",
      desc2: "•	Organizing hybrid labs on topics such as HTML, CSS, Bootstrap, SASS, JS, React, etc. Evaluating and grading assignments",
      desc3: "•	Holding TA hours to answer student questions/doubts about the topics covered in class by Professor",
      rate: "🇺🇸",
    },
    {
      id: 5,
      category: "experience",
      year: "Inquizity, Mumbai (Jan 2020 - Jul 2021) ",
      title: "Senior Software Engineer",
      desc1: "•	Developed and handled the resposibility of new features in the company's core product dataSAVI",
      desc2: "•	Took the ownership of projects from top clients. Contributed in all stages of development from planning to deployement",
      desc3: "•	Being a senior developer, trained and motivated new joinees to work on projects and innovate new things",
      rate: "🇮🇳",
    },
    {
      id: 6,
      category: "experience",
      year: "Inquizity, Mumbai (Jul 2018 - Dec 2019) ",
      title: "Junior Software Engineer",
      desc1: "•	For Indian Railways project, identified a problem statement, developed and implemented QR coding to automate data collection",
      desc2: "•	Engaged in code reviews and debugging, performed manual testing. Handled better code management within the organization using Git",
      desc3: "•	Being a beginner in tech field, passionately learnt tech stack required in the company and performed up to the mark. Also got appreciation from the managers and director of the company",
      rate: "🇮🇳",
    },
  ]
  
  export default ResumeApi